# Generated by Django 2.1b1 on 2018-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
